#!/usr/bin/env bash
# PreToolUse guard: refuse any Write/Edit/MultiEdit targeting a 00-index.md.
# The index is generated by update_doc_index.py only; exit 2 tells Claude Code
# to block the tool call and surface the stderr message to the model.
set -euo pipefail

payload="$(cat || true)"
file_path="$(printf '%s' "$payload" | grep -o '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"file_path"[[:space:]]*:[[:space:]]*"//; s/"$//')"

case "$(basename "$file_path")" in
  00-index.md)
    echo "00-index.md is generated by the doc-index builder; do not edit it by hand. Run .claude/hooks/run-doc-index.sh (or edit the source .md / .indexbuilderinclude.yaml) instead." >&2
    exit 2
    ;;
esac
exit 0
