[project]
name = "vibbix-scripts"
version = "0.1.0"
description = "My personal scripts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pexpect>=4.9.0",
    "rich>=15.0.0",
    "gitpython~=3.1.50",
    "PyGithub~=2.9.1",
    "tqdm~=4.68.2",
    "requests-cache~=1.3.2",
    "colorlog~=6.10.1",
    "colorama~=0.4.6",
    "sourcetypes3~=0.1.0",
    "blessed~=1.44.0",
    # Markdown parsing libraries
    # "mistletoe~=1.5.1",
    "beautifulsoup4~=4.15.0",
    "pasteboard~=0.4.0; sys_platform == 'darwin'",
    "mdutils~=1.8.1",
    # For scraping
    "PyChromeDevTools~=1.0.4",
    # for parsing bazel
    "libcst~=1.8.6",
    # for message box
    "pymsgbox~=2.0.1",
    "jinja2~=3.1.6",
    # for update_index
    "python-frontmatter~=1.3.0",
    "gitignore-parser~=0.1.13",
    "pyrefly>=0.60.0",
    "PyYAML~=6.0.3"
]

[dependency-groups]
dev = [
    "ipykernel~=7.3.0",
    "jupyterlab~=4.5.8",
]

[tool.uv]
exclude-newer = "1 week"
