[project]
name = "vibbix-scripts"
version = "0.1.0"
description = "My personal scripts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pexpect>=4.9.0",
    "rich>=14.0.0",
    "gitpython~=3.1.45",
    "PyGithub~=2.8.1",
    "tqdm~=4.67.1",
    "requests-cache~=1.2.1",
    "colorlog~=6.10.1",
    "colorama~=0.4.6",
    "sourcetypes3~=0.1.0",
    "blessed~=1.25.0",
    # Markdown parsing libraries
    # "mistletoe~=1.5.1",
    "beautifulsoup4~=4.14.3",
    "pasteboard~=0.4.0; sys_platform == 'darwin'",
    "mdutils~=1.8.1",
    # For scraping
    "PyChromeDevTools~=1.0.4",
    # for parsing bazel
    "libcst~=1.8.6",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "jupyterlab>=4.5.2",
]
