#!/usr/bin/env bash
#git remote add upstream
#CHANGELOG:
# [0.0.1]
# - initial version
source "$(dirname "$0")/common.sh"

requires git
requires gh

function gettrunkname() {
  remote=$1
  git symbolic-ref refs/remotes/$remote/HEAD | sed "s@^refs/remotes/$remote/@@"
}

local_url=$(git config remote.origin.url | sed "s/git@\(.*\):\(.*\).git/\1\/\2/")

#todo - finish this
exit 1
# switch to master/main
